# Run before ESP-IDF reads the active configuration or initializes its target.
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/required_config.txt" solar_os_nimble_required_config)

function(solar_os_regenerate_stale_sdkconfig)
    if(SDKCONFIG)
        get_filename_component(config "${SDKCONFIG}" ABSOLUTE)
    else()
        set(config "${CMAKE_SOURCE_DIR}/sdkconfig")
    endif()
    if(NOT EXISTS "${config}")
        return()
    endif()
    file(STRINGS "${config}" bluetooth_enabled REGEX "^CONFIG_BT_ENABLED=y$")
    set(missing_config "")
    foreach(required IN LISTS solar_os_nimble_required_config)
        file(STRINGS "${config}" enabled REGEX "^${required}=y$")
        if(NOT enabled)
            list(APPEND missing_config "${required}")
        endif()
    endforeach()
    if(bluetooth_enabled AND missing_config)
        get_filename_component(config_name "${config}" NAME)
        if(config_name MATCHES "^sdkconfig\\.defaults($|\\.)")
            message(FATAL_ERROR "SDKCONFIG must select a generated configuration, not defaults: ${config}")
        endif()
        message(NOTICE
            "SolarOS BLE configuration missing ${missing_config}; removing stale ${config} and regenerating from SDK configuration defaults")
        file(REMOVE "${config}")
    endif()
endfunction()
