#pragma once

#if defined(SOLAR_OS_BOARD_GENERATED)
#include "solar_os_board_generated.h"
#else
#error "No SolarOS board target selected. Build through a PlatformIO env with a matching boards/manifests/<target>.toml profile."
#endif

#ifndef SOLAR_OS_BOARD_ID
#error "Selected SolarOS board header did not define SOLAR_OS_BOARD_ID."
#endif

#ifndef SOLAR_OS_BOARD_HAS_GPIO
#define SOLAR_OS_BOARD_HAS_GPIO 0
#endif

#ifndef SOLAR_OS_BOARD_GPIO_SLOTS
#if SOLAR_OS_BOARD_HAS_GPIO
#error "Selected SolarOS board header did not define SOLAR_OS_BOARD_GPIO_SLOTS."
#else
#define SOLAR_OS_BOARD_GPIO_SLOTS {{0}}
#endif
#endif

#ifndef SOLAR_OS_BOARD_USER_GPIO_MASK
#define SOLAR_OS_BOARD_USER_GPIO_MASK 0ULL
#endif

#ifndef SOLAR_OS_BOARD_EXPANSION_GPIO_MASK
#define SOLAR_OS_BOARD_EXPANSION_GPIO_MASK 0ULL
#endif

#ifndef SOLAR_OS_BOARD_BUSES
#define SOLAR_OS_BOARD_BUSES {{0}}
#endif

#ifndef SOLAR_OS_BOARD_DEFAULT_EXPANSION_DEVICE_COUNT
#define SOLAR_OS_BOARD_DEFAULT_EXPANSION_DEVICE_COUNT 0
#endif

#ifndef SOLAR_OS_BOARD_DEFAULT_EXPANSION_DEVICES
#define SOLAR_OS_BOARD_DEFAULT_EXPANSION_DEVICES {{0}}
#endif

#ifndef SOLAR_OS_BOARD_DEFAULT_BLE_ENABLED
#define SOLAR_OS_BOARD_DEFAULT_BLE_ENABLED 1
#endif

#ifndef SOLAR_OS_BOARD_HEADLESS_PREFER_CDC
#define SOLAR_OS_BOARD_HEADLESS_PREFER_CDC 0
#endif

#ifndef SOLAR_OS_BOARD_DISPLAY_FRAME_INTERVAL_MS
#define SOLAR_OS_BOARD_DISPLAY_FRAME_INTERVAL_MS 0U
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_TITLE
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_TITLE "Expansion connectors"
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_VIEW
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_VIEW "component-side view"
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_ROWS
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_ROWS 0
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_COLUMNS
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_COLUMNS 0
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_PIN_COUNT
#define SOLAR_OS_BOARD_CONNECTOR_PIN_COUNT 0
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_PINS
#define SOLAR_OS_BOARD_CONNECTOR_PINS {{0}}
#endif

#ifndef SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK
#define SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK 0U
#endif

#ifndef SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK
#define SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK 0U
#endif

#ifndef SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK
#define SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK 0U
#endif

#ifndef SOLAR_OS_BOARD_CPU_FLOOR_MHZ
#define SOLAR_OS_BOARD_CPU_FLOOR_MHZ 0U
#endif

#if SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK && !SOLAR_OS_BOARD_HAS_SPI
#error "SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK requires SOLAR_OS_BOARD_HAS_SPI"
#endif

#if SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK && !SOLAR_OS_BOARD_HAS_EXPANSION_SPI
#error "SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK requires SOLAR_OS_BOARD_HAS_EXPANSION_SPI"
#endif

#if SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK && !SOLAR_OS_BOARD_HAS_UART
#error "SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK requires SOLAR_OS_BOARD_HAS_UART"
#endif

#if SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK && !SOLAR_OS_BOARD_HAS_EXPANSION_UART
#error "SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK requires SOLAR_OS_BOARD_HAS_EXPANSION_UART"
#endif

#if SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK && !SOLAR_OS_BOARD_HAS_EXPANSION_I2S
#error "SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK requires SOLAR_OS_BOARD_HAS_EXPANSION_I2S"
#endif

#ifndef SOLAR_OS_BOARD_EXPANSION_ADC_MASK
#define SOLAR_OS_BOARD_EXPANSION_ADC_MASK 0ULL
#endif

#ifndef SOLAR_OS_BOARD_EXPANSION_PWM_MASK
#define SOLAR_OS_BOARD_EXPANSION_PWM_MASK 0ULL
#endif
