[flavor]
name = "netrunner"
description = "Minimal SolarOS build with hardware services, and network tools."

[groups]
hardware_shell = true
filesystem = true
wifi = true
bluetooth = true
sd_storage = true
audio_support = true
control_bindings = true
signal_processing = true
vector_math = true
gpio = true
onewire = true
i2c = true
spi = true
uart = true
adc = true
pwm = true
board_buttons = true
adc_dpad = true
documentation_sync = true
device_flasher = true
logging = true
battery_monitor = true
embedded_docs = true
serial_terminal = true
editor = true
pager = true
files = true
launcher = true
io = true
sump = true
bridge = true
daq = true
gpio_keys = true
ps2_keyboard = true
midi = true
ssh = true
http_client = true
web_browser = true
ftp = true
telnet = true
http_server = true
display_server = true
wireguard = true
mqtt = true
ntp = true
slip = true
osc = true
inbox = true
contacts = true
chat = true
chat_gateway = true
gateway_sync = true
chat_server = true
email = true
agent = true
espnow = true
pocsag = true
radio_link = true
meshcore = true
webradio = true
rfm69 = true
rfm95 = true
pcd8544 = true
ssd1683 = true
ssd1306 = true
cardkb = true
analog_joystick = true
ps2_mouse = true
sdspi = true
sdmmc = true
neopixel = true
audio_pwm = true
pcm5102 = true
pcm1808 = true
