[flavor]
name = "custom"
description = "Custom SolarOS flavor created with os_builder."

[groups]
hardware_shell = true
filesystem = true
wifi = true
bluetooth = true
sd_storage = true
audio_support = true
control_bindings = true
signal_processing = true
vector_math = true
gpio = true
onewire = true
i2c = true
spi = true
uart = true
adc = true
pwm = true
board_buttons = true
adc_dpad = true
logging = true
embedded_docs = true
serial_terminal = true
editor = true
pager = true
files = true
launcher = true
io = true
clock = true
calculator = true
plot = true
sheet = true
bridge = true
gpio_keys = true
ps2_keyboard = true
ssh = true
http_client = true
web_browser = true
ftp = true
telnet = true
wireguard = true
mqtt = true
ntp = true
slip = true
osc = true
inbox = true
contacts = true
chat = true
chat_gateway = true
gateway_sync = true
espnow = true
radio_link = true
meshcore = true
audio_commands = true
reader = true
writer = true
notes = true
image_viewer = true
rfm69 = true
rfm95 = true
analog_joystick = true
ps2_mouse = true
sdspi = true
sdmmc = true
audio_pwm = true
pcm5102 = true
pcm1808 = true
