#pragma once

#define SOLAR_OS_PACKAGE_APP_READER 0
#define SOLAR_OS_PACKAGE_APP_WEB 0
#define SOLAR_OS_PACKAGE_APP_PYTHON 1
#define SOLAR_OS_PACKAGE_APP_LUA 1
#ifndef SOLAR_OS_PACKAGE_SERVICE_DOCS
#define SOLAR_OS_PACKAGE_SERVICE_DOCS 0
#endif
#define SOLAR_OS_PACKAGE_EXPANSION_SDSPI 0
#define SOLAR_OS_PACKAGE_EXPANSION_SDMMC 0
